version: "3"
services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpressDB:/var/www/html
    build: ./requirements/nginx
    networks:
      - network
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    volumes:
      - mariaDB:/var/lib/mysql
    build: ./requirements/mariadb
    networks:
      - network
    env_file: .env
    ports:
      - "3306:3306"
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    volumes:
      - wordpressDB:/var/www/html
    build: ./requirements/wordpress
    networks:
      - network
    env_file: .env
    restart: always
    depends_on:
      - mariadb
    ports:
      - "9000:9000"

volumes:
  wordpressDB:
    driver: local
  mariaDB:
    driver: local

networks:
  network:
    driver: bridge
