FROM	debian:bullseye

RUN		apt-get update && apt-get upgrade

RUN		apt-get install -y php7.3\
		curl \
		php-fpm \
		php-mysql

RUN		apt-get install mariadb-server -y


COPY ./tools/script.sh /

RUN chmod +x script.sh

EXPOSE 9000

CMD [ "bash" , "/script.sh" ]